### ISSUE TITLE
Could us minimize the role permission set

### ISSUE THREAD

**Issue by Colstuwjx** [mnlth1/functionbeat#1]
Hi @mnlth1 

Many thanks to your [post](https://dev.to/mnlth/functionbeat-for-streaming-cloudwatch-events-to-elasticsearch-l5j), I'm also  planning to use functionbeat to collect aws cloudwatch logs, but I've met  a problem that the required iam roles is tooooo big, see the [iam yaml](https://github.com/mnlth1/functionbeat/blob/master/sample/functionbeat-iam.yml#L25), it even give **iam:*** such unlimited privilges!

Again, could us minimize the role permission set?

**Comment by mnlth1** [comment]
Hi @Colstuwjx, glad you found the example helpful. Yes, you can narrow down the role permissions to only require actions as defined here - https://www.elastic.co/guide/en/beats/functionbeat/current/iam-permissions.html

**Comment by mnlth1** [comment]
Since there's required details mentioned above, closing the issue
